layout_spectrum: 0.0227281
color:
  saturation: 0.3005193
  brandStrength: 0
  lightness: 0.08888525
  rhythmicContrast: 0.5418855
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.5290449
name: Beyond IG
