name: Beyond IG
favicon: null
layout_spectrum: 0.0227281
typography_spectrum: 0.74992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0
  lightness: 0.08888525
  saturation: 0.3005193
  rhythmicContrast: 0.5418855
purpose: []
